[code-infra] Add retry loop around continuous releases

diff --git a/.github/actions/ci-publish/action.yml b/.github/actions/ci-publish/action.yml
--- a/.github/actions/ci-publish/action.yml
+++ b/.github/actions/ci-publish/action.yml
@@ -20,4 +20,18 @@ runs:
     - name: Publish to pkg.pr.new
       shell: bash
       run: |
-        pnpm dlx pkg-pr-new publish $(pnpm code-infra list-workspaces --public-only --output=publish-dir) --pnpm --packageManager=pnpm --peerDeps --template './examples/*' --comment=${{ inputs.pr-comment == 'true' && 'update' || 'off' }} ${{ inputs.use-compact-url == 'true' && '--compact' || '' }}
+        for i in 1 2 3; do
+          
+          pnpm dlx pkg-pr-new publish $(pnpm code-infra list-workspaces --public-only --output=publish-dir) --pnpm --packageManager=pnpm --peerDeps --template './examples/*' --comment=${{ inputs.pr-comment == 'true' && 'update' || 'off' }} ${{ inputs.use-compact-url == 'true' && '--compact' || '' }}
+
+          exit_code=$?
+          if [ $exit_code -eq 0 ]; then
+            break
+          elif [ $i -eq 3 ]; then
+            echo "Command failed after $i attempts with exit code $exit_code."
+            exit $exit_code
+          else
+            echo "Attempt $i failed (exit code $exit_code), retrying..."
+            sleep 5
+          fi
+        done
